name: apiverve_cardvalidator
description: Card Validator is a simple tool for validating if a card number is valid or not. It checks the card number format and the Luhn algorithm to see if the card number is valid.
version: 1.1.14
homepage: https://apiverve.com/marketplace/cardvalidator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/cardvalidator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
